//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UlianenkoprEntities : DbContext
    {
        public UlianenkoprEntities()
            : base("name=UlianenkoprEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<ReadingList> ReadingLists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<RoleRequest> RoleRequests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UnfreezeRequest> UnfreezeRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
